start-x: 4500
start-y: 300
width: 2560
height: 1440

layout:

    - hgroup:

      - title: Our Groceries
        url: https://www.ourgroceries.com/your-lists/list/MQ0VcOZaQr8UyWjeVQABSk
        width: 330

      - title: Todoist Chores
        url: https://app.todoist.com/app/section/chores-6fh448CQc2C2CQG7
        width: 445


      - vgroup:

        - title: Google Calendar
          url: https://calendar.google.com

        - title: Google Photos
          url: https://photos.google.com


      - vgroup:

        - hgroup:

          - title: MSN Weather
            url: https://www.msn.com/widgets/fullpage/weatherWidgets/widget?experiences=WeatherCardWCFull
            width: 450
            height: 300

          - title: Google Home
            url: https://google.com

        - title: Google Home
          url: https://google.com
